# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            hyper-cube.io
tagline:          'A Jekyll theme'
description:      'desc'
url:              http://hyper-cube.io
baseurl:          /

authors:
  jh:
    name: Jihoon Kim
    display_name: Jihoon
    gravatar: 08c3aa66b58fccc84f072d8e9848e69b
    email: jh.kim@hyper-cube.io
    web: http://ium.me
    twitter: _super_fishz
    github: super-fishz

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hyper-cube-io/hyper-cube-io
