# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            hyper-cube.io
tagline:          'A Jekyll theme'
description:      'desc'
url:              http://hyper-cube.io
baseurl:          /

authors:
  jh:
    name: Jihoon Kim
    display_name: Jihoon
    email: jh.kim@hyper-cube.io
    web: http://ium.me
    twitter: _super_fishz
    github: super-fishz
  sh:
    name: Seungsoo Han
    display_name: Seungsoo
    github: hanseungsoo
    email: hss0417@gmail.com
  kwSeo:
    name: Kyeongwon Seo
    display_name: kwSeo
    email: tkruddnjs1@naver.com
    web: http://kwSeo.github.io
    github: kwSeo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hyper-cube-io/hyper-cube-io
